import type { PushFrame, RequestFrame } from '../types';

const playerUid = 'Player-7' as const;
const npcUid = 'NPC-3' as const;

export const REQUEST_FIXTURES = [
  { uid: playerUid, uri: 'ping', method: null, data: {} },
  {
    uid: playerUid,
    uri: 'command.auth.Register',
    method: null,
    data: { nickname: 'Ada', email: 'ada@example.test', cryptoPWD: 'secret' },
  },
  {
    uid: playerUid,
    uri: 'command.building.Create',
    method: null,
    data: { building_type: 'house', name: 'Home', x: 1, y: 2, rotation: 0 },
  },
  { uid: playerUid, uri: 'command.building.GetBuildings', method: null, data: {} },
  {
    uid: playerUid,
    uri: 'command.building.GetBuildingInfo',
    method: null,
    data: { buildingID: 9 },
  },
  {
    uid: playerUid,
    uri: 'command.npc.Create',
    method: null,
    data: {
      asset: 'agent',
      model: 'model',
      memorySystem: 'memory',
      planSystem: 'plan',
      homeBuilding: 1,
      workBuilding: 2,
      nickname: 'Bob',
      bio: 'bio',
      goal: 'goal',
      cash: 10,
    },
  },
  { uid: playerUid, uri: 'command.npc.GetNPCs', method: null, data: {} },
  { uid: playerUid, uri: 'command.npc.GetNPCInfo', method: null, data: { NPCID: 3 } },
  {
    uid: playerUid,
    uri: 'command.npc.ChangePrompt',
    method: null,
    data: { NPCID: 3, promptType: 'plan', promptText: 'new plan' },
  },
  { uid: playerUid, uri: 'command.map.Navigate', method: null, data: { x: 3, y: 4 } },
  { uid: playerUid, uri: 'command.map.GetMapScene', method: null, data: {} },
  { uid: playerUid, uri: 'command.map.GetMapTown', method: null, data: {} },
  {
    uid: playerUid,
    uri: 'command.chat.ChatWithNPC',
    method: null,
    data: { NPCID: npcUid, content: 'hello' },
  },
  { uid: playerUid, uri: 'command.player.GetPlayerInfo', method: null, data: {} },
  { uid: playerUid, uri: 'command.mayor.GetInfo', method: null, data: {} },
  { uid: playerUid, uri: 'command.config.GetBuildingsConfig', method: null, data: {} },
  { uid: playerUid, uri: 'command.config.GetNPCsConfig', method: null, data: {} },
  { uid: playerUid, uri: 'command.config.GetEquipmentsConfig', method: null, data: {} },
  { uid: playerUid, uri: 'command.timetick.Tick', method: null, data: {} },
  { uid: playerUid, uri: 'command.starter.TickStarter', method: null, data: {} },
  { uid: playerUid, uri: 'command.starter.MayorStarter', method: null, data: {} },
  { uid: playerUid, uri: 'command.gm.FakeSendings', method: null, data: { testName: 'movePath' } },
] satisfies readonly RequestFrame[];

const building = {
  id: 4,
  n: 'Library',
  o: playerUid,
  t: 'library',
  lx: 0,
  ty: 0,
  rx: 2,
  by: 2,
  r: 0,
  x: 1,
  y: 1,
  eI: 0,
  eE: 0,
  eT: 0,
  hL: [],
  hC: 0,
  lL: [],
  lC: 0,
  rI: 2,
  rT: 3,
} as const;

export const PUSH_FIXTURES = [
  { code: 200, uri: 'welcome' },
  { code: 200, uri: 'movePath', data: { uid: npcUid, path: [{ x: 1, y: 2 }] } },
  { code: 200, uri: 'moveTo', data: { uid: npcUid, fromX: 1, fromY: 2, toX: 3, toY: 4 } },
  { code: 200, uri: 'NPC-React', data: { uid: npcUid, reaction: 'thinking' } },
  { code: 200, uri: 'newPlan', data: { uid: npcUid, plan: 'visit library' } },
  {
    code: 200,
    uri: 'planToMove',
    data: { uid: npcUid, targetBuilding: 'Library', targetBuildingID: 4 },
  },
  { code: 200, uri: 'chatWith', data: { sourceID: playerUid, targetID: npcUid, content: 'hello' } },
  {
    code: 200,
    uri: 'interact',
    data: { uid: npcUid, equipment: 1, operation: 'read', continueTime: 3, cost: 1, earn: 2 },
  },
  { code: 200, uri: 'newAction', data: { uid: npcUid, action: 'read' } },
  {
    code: 200,
    uri: 'finishAction',
    data: { uid: npcUid, action: 'read', startTime: 1, endTime: 2 },
  },
  { code: 200, uri: 'changeCash', data: { uid: npcUid, cash: 11, amount: 1, effect: 'increase' } },
  {
    code: 200,
    uri: 'changeRevenue',
    data: { uid: playerUid, revenue: 12, amount: 2, effect: 'increase' },
  },
  {
    code: 200,
    uri: 'increaseBuildingIncome',
    data: { uid: playerUid, building_id: 4, income: 3, amount: 1 },
  },
  {
    code: 200,
    uri: 'mayor.npc.Create',
    data: {
      uid: npcUid,
      homeBuilding: 1,
      asset: 2,
      assetName: 'agent',
      model: 'model',
      memorySystem: 'memory',
      planSystem: 'plan',
      workBuilding: null,
      nickname: 'Bob',
      bio: 'bio',
      goal: 'goal',
      cash: 10,
      x: 3,
      y: 4,
    },
  },
  { code: 200, uri: 'mayor.building.Create', data: building },
] satisfies readonly PushFrame[];
